3 rewrite login desktop
aidportaliug/IUG-projects pull request #24
Opened 2024-02-13 13:39 UTC by ESPR07

Rewritten the login page to closely match the figma design, It's now made with responsiveness in mind, but Mobile version is not implemented yet.

Closes #3

2024-02-13 14:59 UTC, AKissMail requested changes
Hi, I located some cosmetic issues. I left you some comments.

2024-02-13 14:59 UTC, AKissMail commented on src/components/Login.tsx
>            <Typography component="h1" variant="h5">
You could fix the display issue with 
```html
<h1 className="signupH1">Log in to Projects Without Borders</h1>

```

2024-02-13 14:59 UTC, AKissMail commented on src/styles/login.css
> +  font-weight: bolder;
What about 800 for the font weight and we have a global setting for the font family in main.css 
```css
.loginText,
.signupText {
  color: var(--mainGreen);
  font-size: min(3vw, 1.7rem);
  font-weight: 800;
  align-items: center;
  margin-inline: 30px;
  font-family: var(--mainFontFamily);
}

```

2024-02-13 14:59 UTC, AKissMail commented on src/styles/login.css
> +.signupRedirect {
Here I also suggest to uses the global property a bit more font weight
```css
.signupRedirect {
  width: 90%;
  text-align: end;
  font-family: var(--mainFontFamily);
  font-weight: bolder;
}
```

2024-02-13 14:59 UTC, AKissMail commented on src/styles/login.css
>  }
New class needed if you accept my suggestion for the heading: 
```css
.signupH1 {
  font-family: var(--mainFontFamily);
  font-size: 25pt;
}
```

2024-02-13 17:39 UTC, ESPR07 commented on src/components/Login.tsx
>            <Typography component="h1" variant="h5">
This has been added and fixed :D

2024-02-15 17:08 UTC, AKissMail reviewed
Nice!

2024-02-15 17:09 UTC, AKissMail approved these changes

2024-02-15 17:09 UTC, merged